local plugin = require("my_awesome_plugin")

describe("my_awesome_plugin with default", function()
  it("can compute max", function()
    plugin.setup({})
    assert.equals(3, plugin.main(2.5, 2.4, "max"))
    assert.equals(3, plugin.main(2.4, 2.5, "max"))
  end)
  it("can compute min", function()
    plugin.setup({})
    assert.equals(2, plugin.main(2.5, 2.4, "min"))
    assert.equals(2, plugin.main(2.4, 2.5, "min"))
  end)
end)

describe("my_awesome_plugin with custom options", function()
  it("can compute max", function()
    plugin.setup({ round = false })
    assert.equals(2.5, plugin.main(2.5, 2.4, "max"))
    assert.equals(2.5, plugin.main(2.4, 2.5, "max"))
  end)
  it("can compute min", function()
    plugin.setup({ round = false })
    assert.equals(2.4, plugin.main(2.5, 2.4, "min"))
    assert.equals(2.4, plugin.main(2.4, 2.5, "min"))
  end)
end)
