local love2d = require("love2d")

describe("love2d mac", function()
  it("does not start with wrong path_to_love", function()
    love2d.setup({ path_to_love = "/Applications/love.app/Contents/MacOS/foo" })
    love2d.run("tests/game")
    vim.wait(1000)
    assert.equal(nil, love2d.job.id)
    vim.wait(500)
  end)
  it("starts", function()
    love2d.setup({ path_to_love = "/Applications/love.app/Contents/MacOS/love" })
    love2d.run("tests/game")
    vim.wait(1000)
    assert.equal(1, vim.fn.jobstop(love2d.job.id))
    vim.wait(500)
  end)
  it("does not run foo with wrong path to game", function()
    love2d.setup({ path_to_love = "/Applications/love.app/Contents/MacOS/love" })
    love2d.run("tests/foo")
    vim.wait(1000)
    assert.equal(1, vim.fn.jobstop(love2d.job.id))
    vim.wait(500)
    assert.equal(1, love2d.job.exit_code)
  end)
  it("runs game", function()
    love2d.setup({ path_to_love = "/Applications/love.app/Contents/MacOS/love" })
    love2d.run("tests/game")
    vim.wait(1000)
    assert.equal(1, vim.fn.jobstop(love2d.job.id))
    vim.wait(500) -- wait for on_exit to be called
    assert.equal(0, love2d.job.exit_code)
  end)
end)
