name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "2.4.1"
          args: --check lua/ spec/

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mrcjkb/lua-typecheck-action@v1.1.0
        with:
          directories: lua/
          checklevel: Warning
          configpath: .luarc.json
