name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "2.4.1"
          args: --check lua/ spec/

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: setup-vim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v1.1.0
        env:
          VIM: ${{ steps.setup-vim.outputs.vim-directory }}
        with:
          directories: lua/
          checklevel: Warning
          configpath: .luarc.json
