name: Code Quality
on:
  pull_request: ~
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  luacheck:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      - name: Lint
        run: luacheck lua/
  stylua:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua
  typecheck:
    name: Typechecker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # Neovim types, maybe there is a better way
      - name: Checkout dependency neodev
        uses: actions/checkout@v3
        with:
          repository: "folke/neodev.nvim"
          path: "deps/neodev.nvim"
      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0
        with:
          checklevel: Warning
          configpath: .github/workflows/.luarc.json
          directories: |
            lua
            spec
